import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

/* Standalone host — deliberately mounted under a non-root base so asset and
   route handling cannot rely on "/". */
export default defineConfig({
  root: fileURLToPath(new URL(".", import.meta.url)),
  base: "/mh-host/",
  /* examples/host/public is generated by scripts/build-host.mjs (copies of
     assets/images + assets/fonts) — never committed. */
  publicDir: fileURLToPath(new URL("./public", import.meta.url)),
  plugins: [react()],
  build: { outDir: "dist" },
});
