/** Generated by scripts/compose_portal.py. */
import home from "./trees/home.json";
import campaign from "./trees/campaign.json";
import data_model from "./trees/data-model.json";
import data_upload from "./trees/data-upload.json";
import feedback_quality from "./trees/feedback-quality.json";
import flexible from "./trees/flexible.json";
import knowledge_create from "./trees/knowledge-create.json";
import knowledge_view from "./trees/knowledge-view.json";
import knowledge from "./trees/knowledge.json";
import media_tracking_detail from "./trees/media-tracking-detail.json";
import metric_dictionary from "./trees/metric-dictionary.json";
import personal_memory from "./trees/personal-memory.json";
import reports from "./trees/reports.json";
import review_center from "./trees/review-center.json";
import scenario_detail from "./trees/scenario-detail.json";
import scenario_edit from "./trees/scenario-edit.json";
import scenario_library from "./trees/scenario-library.json";
export const trees = {
  "home": home,
  "campaign": campaign,
  "data-model": data_model,
  "data-upload": data_upload,
  "feedback-quality": feedback_quality,
  "flexible": flexible,
  "knowledge-create": knowledge_create,
  "knowledge-view": knowledge_view,
  "knowledge": knowledge,
  "media-tracking-detail": media_tracking_detail,
  "metric-dictionary": metric_dictionary,
  "personal-memory": personal_memory,
  "reports": reports,
  "review-center": review_center,
  "scenario-detail": scenario_detail,
  "scenario-edit": scenario_edit,
  "scenario-library": scenario_library,
};
