import { knowledgeCreateTypes } from "../../knowledge-create-options.js";
import { demoImage } from "../images.js";

/** P08 copy and deterministic local fixtures, transcribed from the effective forms. */
export const KNOWLEDGE_CREATE = {
  navigation: [
    { id: "home", label: "Home" },
    { id: "cockpit", label: "Marketing Cockpit" },
    { id: "selfService", label: "Self-Service Center" },
    { id: "interpreter", label: "AI Interpreter" },
    { id: "campaign", label: "RedNote Campaign Tool" },
  ],
  types: knowledgeCreateTypes,
  identity: { currentUser: "Current User" },
  labels: {
    management: "Knowledge Management", eyebrow: "KNOWLEDGE MANAGEMENT", create: "Create New Knowledge",
    genericDescription: "Create governed knowledge using a structured form.", draft: "Draft", type: "Knowledge Type",
    cancel: "Cancel", save: "Save", submit: "Submit", required: "This field is required.",
    savedTitle: "Saved successfully", savedText: "Your knowledge draft has been saved.",
    submittedTitle: "Submitted successfully", submittedText: "Your knowledge has been submitted for review.",
    back: "Back to Knowledge Management", invalid: "Complete the required fields before continuing.",
    edit: "Edit Knowledge", editReport: "Edit", copy: "Copy Knowledge", enabled: "Enable knowledge",
    home: "Home", interpreter: "AI Interpreter", breadcrumb: "Breadcrumb", editTerm: "Edit",
    editAnalysis: "Edit Analysis", editScenario: "Edit Scenario Reporting", close: "Close",
    confirmTitle: "Submit description update?", confirmText: "This will submit the updated report description for review.",
    guidanceTitle: "Structure & Guidance", testTitle: "Test Run", smartTitle: "Smart Modeling", previewTitle: "Preview Data",
    testSuccessTitle: "Test completed", testEmptyTitle: "Formula required", testSuccess: "Formula executed successfully. Aggregated result: 1,284.60.", testEmpty: "Please build a formula before testing.",
    smartText: "Smart Modeling has prepared a configuration draft.", previewText: "Preview data is ready for this model.",
    historyTitle: "Report description history", currentVersion: "Current version", previousVersion: "Previous version",
  },
  shared: {
    businessDomains: ["Marketing", "C360", "Retail Operations", "Data Governance"],
    reports: ["City Strategy", "4P Report", "Customer Daily Tracking", "ABO", "Rednote Tracking"],
    datasets: ["Marketing DW", "Campaign Performance", "Customer 360", "Commerce Performance"],
    scope: ["Marketing", "Customer", "Retail Operations", "Data Governance", "City Strategy", "Commerce", "Revenue Dashboard", "Sales Performance", "Sales Performance Report", "Customer 360", "Conversion Overview", "Member Performance", "4P Report", "Customer Daily Tracking", "ABO", "Rednote Tracking", "OTT/OLV Media Data Tracking", "Global", "All reports"],
    reportLinks: ["Invest City Strategy Analysis", "City Analysis Dashboard", "4P Executive Overview", "Promotion Lift Analysis", "Customer Daily Pulse", "Customer Funnel Watch", "Audience Build Overview", "Campaign Quality Watch", "Rednote Media Tracking", "Creative Quality Monitor", "OTT / OLV Exposure Tracking", "Source Integrity Monitor"],
    basicMetrics: [
      ["Exposure Count", "fact_promotion_daily.exposure_count"], ["Visit Count", "fact_promotion_daily.visit_count"],
      ["Add to Cart Count", "fact_promotion_daily.add_to_cart_count"], ["Promotion Attributed Orders", "fact_promotion_daily.order_count"],
      ["Store Visit Customers", "fact_promotion_daily.store_visit_customers"], ["Promotion Attributed Sales", "fact_promotion_daily.sales_amount"],
      ["Promotion Spend", "fact_promotion_daily.promotion_cost"],
    ],
    modelTables: {
      entity: [
        { id: "dim_channel", title: "Channel Dimension", meta: "7 rows", fields: [
          ["channel_id", "int", "Channel ID", "Channel Key"], ["channel_code", "varchar(32)", "Channel Code", "Channel Code"],
          ["channel_name", "varchar(50)", "Channel Name", "Channel, Channel name"], ["channel_group", "varchar(20)", "Channel Group", "Channel type, Sales channel"],
          ["online_offline", "varchar(20)", "Online / Offline", "Online, Offline"],
        ] },
        { id: "dim_customer", title: "User & Member Dimension", meta: "1,320 rows" },
        { id: "dim_date", title: "Date Dimension", meta: "581 rows" },
        { id: "dim_product", title: "Product SKU Dimension", meta: "36 rows" },
        { id: "dim_region", title: "Region Dimension", meta: "12 rows" },
      ],
      event: [{ id: "fact_media_performance", title: "Media Performance Event", meta: "58,420 rows", fields: [
        ["event_id", "bigint", "Event ID", "Performance Event"], ["event_date", "date", "Event Date", "Activity Date"],
        ["media_channel", "varchar(50)", "Media Channel", "Channel"], ["impressions", "decimal(18,2)", "Impressions", "Exposure"],
        ["spend", "decimal(18,2)", "Media Spend", "Investment"],
      ] }],
    },
  },
  model: {
    defaultDescription: "Master data for marketing channel attributes and channel classifications.",
    dataSource: "Marketing DW", groups: { entity: "Entity · 6", event: "Event · 1" },
    basicTabs: { basic: "Basic Info", fields: "Field Config" },
    tableHeaders: ["FIELD", "NAME", "SYNONYMS", "FIELD TYPE", "SEMANTIC ROLE", "FUZZY MATCH", "DEFAULT AGGREGATION"],
    fieldTypes: ["Dimension", "Measure", "Identifier"], roles: ["Category", "Metric", "Hierarchy"],
  },
  synonyms: {
    existing: [["East China Region","East China","Dimension","Marketing","City Strategy","Marketing DW","Enabled"],["Gross Sales Value","GSV","Metric","Marketing","4P Report","Campaign Performance","Enabled"],["Gross Sales Value","Sales Amount","Metric","Retail Operations","Customer Daily Tracking","Commerce Performance","Enabled"],["Channel","Media Channel","Dimension","Marketing","City Strategy","Marketing DW","Enabled"],["Member Segment","Customer Tier","Enumeration","Customer Growth","Customer Daily Tracking","Customer 360","Enabled"]],
    kinds: ["Metric", "Dimension", "Enumeration"],
    headers: ["STANDARD TERM *","SYNONYM *","TERM TYPE *","APPLICABLE BUSINESS DOMAIN","APPLICABLE REPORTS","RELATED DATASETS","STATUS","ACTIONS"],
    choices: { domain: ["Marketing", "Customer Growth", "Retail Operations", "Data Governance"], reports: ["City Strategy", "4P Report", "Customer Daily Tracking", "ABO", "Rednote Tracking"], dataset: ["Marketing DW", "Campaign Performance", "Customer 360", "Commerce Performance"] },
  },
  reportHistory: { author: "Current User", priorAuthor: "Data Governance", priorDate: "Jul 24, 2026", priorDescription: "Updated parameter sources and reporting guardrails." },
  copy: {
    scopeDomain: "Applicable Business Domain", scopeReports: "Applicable Reports", relatedDatasets: "Related Datasets",
    knowledgeEnabled: "Enable knowledge", selectMany: "Select one or more", required: "This field is required.",
    metricDomain: "Business Domain", metricName: "Metric Name", unit: "Unit", formula: "Formula Builder", formulaRequired: "Please build a formula first.",
    formulaHint: "Build the formula by clicking referenceable basic metrics and operators.", testRun: "Test Run", removeMetric: "Remove metric",
    testHint: "Test will execute the formula and return a single aggregated result.", test: "Test", description: "Description", synonyms: "Synonyms", metricStatus: "Status:", metricStatusOn: "Enable", metricStatusOff: "Disable", metricsHeading: "REFERENCEABLE BASIC METRICS",
    modelName: "Model Name", modelDescription: "Model Description", modelEnabled: "Enable Model", aiModeling: "AI Modeling", beta: "BETA",
    aiModelingHint: "Generate data model configuration drafts through AI assistant. Results will sync to the table and field configuration area below.", smartModeling: "Smart Modeling",
    tableSearch: "Search table name or description...", dataSourceHeading: "DATA SOURCE", enabled: "Enabled", preview: "Preview Data",
    tableName: "Table Name", physicalTable: "Physical Table", tableDescription: "Table Description", tableType: "Table Type", dataSource: "Data Source", enableTable: "Enable table", enterSynonym: "Enter synonym",
    synonymManagement: "Synonym Management", synonymIntro: "Maintain global language mappings so AI can understand different business expressions.", addSynonym: "Add Synonym", synonymHint: "New rows appear at the top. Complete required fields before submitting.",
    standardTerm: "Standard term", termType: "Term type", select: "Select", applicableDomain: "Applicable domain", relatedDataset: "Related dataset", status: "Status", removeRow: "Remove row", readOnly: "Read only", disabled: "Disabled",
    reportPreview: "Report preview unavailable", reportDescription: "REPORT DESCRIPTION", reportContext: "Report Context", reportDataModel: "Data Model", unlockReport: "Unlock report description", lockReport: "Lock report description", versionHistory: "Version history", reportEditable: "You can now update the report description.", reportLocked: "Unlock the description to edit this governed report context.", aiStatus: "AI Interpreter Status", aiSummary: "AI Summary", scenarioReports: "Scenario Reports", reportScope: "Report Data Scope", reportScopeEmpty: "Report data scope has not been configured.",
    basicInformation: "Basic Information", analysisName: "Analysis Name", triggerWhen: "Trigger When", metrics: "Metrics", referencedMetrics: "Referenced Metrics", structureGuidance: "Structure & Guidance", constraints: "Constraints", prohibitedDirections: "Prohibited Analysis Directions", showGuidance: "Show Structure and Guidance prompt",
    scenarioName: "Scenario Reporting Name", relatedReport: "Related Report", upload: "Upload reference", uploadHint: "Show how this scenario reporting should be written. You can upload reports, screenshots, slides, or documents.", statusHint: "AI Interpreter Status is enabled automatically when processing reaches Published.",
    knowledgeTitle: "Knowledge Title", coreDescription: "Core Description", dashboardDescription: "Dashboard Description", aiOverview: "Enable AI Overview", aiOverviewOff: "Disable AI Overview", aiDescription: "AI Overview Description", aiSources: "AI Overview Parameter Sources",
  },
  options: { metricDomains: ["Marketing", "Customer Growth", "Retail Operations"], aiSources: ["Marketing DW", "Campaign Performance", "Customer 360"], synonymStatuses: ["Enabled", "Disabled"] },
  metricOperators: ["+", "−", "×", "÷", "(", ")", "123"],
  placeholders: {
    metricDomain: "Select a business domain", metricName: "Enter metric name...", unit: "e.g. USD, %, count", formula: "Click a metric or operator to build your formula...", metricDescription: "Describe the metric purpose and calculation logic...", metricSynonyms: "Comma separated",
    modelName: "Enter model name", modelDescription: "Describe the purpose and scope of this data model", modelSearch: "Search table name or description...", synonym: "Enter synonym",
    analysisName: "Enter a name for this new analysis.", analysisDescription: "Briefly state the business goal, decision to support, and expected insight. Do not list analysis steps here.", triggerWhen: "Describe the user questions, business events, or conditions that should trigger this analysis.", domainTags: "Type and press Enter; use semicolons for multiple values", constraints: "State unsupported dimensions, missing data and conclusions AI must avoid.",
    scenarioName: "Enter scenario reporting name", relatedReport: "Select a report", scenarioDescription: "Describe this scenario report's use case and main purpose, so it is easy to reference later.", principlesTitle: "Enter knowledge title", principlesDescription: "Describe the principle and rule details",
  },
  businessTerm: {
    title: "Create Business Term", guidanceTitle: "Build a common language",
    guidance: "Clearly define the meaning, usage, and boundaries of this business term to help teams talk about data consistently.",
    reminder: "Operation reminder: Save keeps this term in Draft. Submit publishes it for AI use.",
    labels: { title: "Title", kind: "Term Type", description: "Description", synonyms: "Synonyms", scope: "Data Model", select: "Select one or more", cancel: "Cancel", save: "Save", submit: "Submit", required: "This field is required." },
    placeholders: { title: "Enter the business term title.", description: "Explain the meaning, usage, and boundary of this term.", synonyms: "Add aliases, abbreviations, or equivalent terms, separated by commas." },
  },
  analysis: {
    title: "Create Analysis", description: "Describe a reusable analysis framework.",
    unavailable: "This analysis is unavailable or you do not have permission to edit it. Return to Analytical Model to select another record.",
    guidance: "Describe the analysis logic and reasoning path. Focus on how to analyze the question and what final result should be returned. Do not ask AI to create charts or extra report sections.\n\nFor example:\n1. Confirm the user's business question, analysis period, target scope and comparison baseline.\n2. Check whether the selected metrics changed materially, and identify the main direction of the change.\n3. Compare related dimensions or segments to locate the most likely driver of the change.\n4. Judge whether the evidence supports a clear cause. If not, explain the limitation.\n5. Return one concise analysis result with the key finding, reason and recommended next action.",
    reminder: "Operation reminder: Save keeps this model disabled. Submit publishes it using the selected AI Interpreter Status.",
    metrics: ["Member conversion", "Campaign ROI", "Promotion lift"],
  },
  scenario: {
    title: "Create Scenario Reporting", description: "Use a related report, supporting materials, and a structure note to define how this report should be written.",
    guidance: "Describe the report structure, what each section should cover, and any chart, table, or style requirements.\n\nFor example:\n1. An executive summary.\n2. Show sales and traffic trends by city with a line chart for the reporting period and a bar chart for city comparison. Include a compact table with clear column headers, right-aligned numeric values, and rankings by sales, conversion rate, and traffic.\n3. Explain abnormal cities and give action recommendations.\n4. Conclusions or recommendations.",
    reminder: "Operation reminder: Save keeps this scenario in Draft. Submit sends it to Queued first, then Building.",
  },
  records: {
    "investment-principles": { type: "Principles", title: "Campaign investment decision principles", description: "Shared guardrails for evaluating investment pressure, conversion efficiency, and the confidence required before recommending action.", businessDomain: [], enabled: true },
    "business-term-gmv": { type: "Business Term", title: "GMV (Gross Merchandise Value)", kind: "Business Term", description: "Total value of merchandise sold through the platform before deductions.", synonyms: "Gross Sales, Merchandise Value, Gross Merchandise Sales", scope: ["Commerce", "Revenue Dashboard", "Sales Performance"] },
    "global-synonym-revenue": { type: "Business Term", title: "Revenue", kind: "Global Synonym", description: "Global aliases used to recognize governed revenue-related questions.", synonyms: "Sales, Turnover, Income", scope: [] },
    "city-report-context": { type: "Report Context", title: "Invest City Strategy Analysis", description: "Purpose, audience, comparison logic, and guardrails for the Invest City Strategy report.", originalDescription: "Purpose, audience, comparison logic, and guardrails for the Invest City Strategy report.", updatedAt: "3 days ago", businessDomain: ["City Strategy"], ai_interpretation_enabled: true, ai_summary_enabled: true, status: true, thumbnail: demoImage("assets/images/project-city-tabby.png"), scenarioReports: ["scenario-channel-performance", "scenario-campaign-review"], reportScope: "Covers the selected invest cities, reporting period and comparable stores. Includes governed traffic, sales, conversion and basket metrics. Excludes test stores, cancelled transactions and returns; incomplete periods must be identified." },
    "playbook-opportunity-scan": { type: "Analytical Model", created_by: "Current User", analysis_name: "Opportunity scan playbook", description: "Repeatable routine for identifying and prioritizing growth opportunities across channels and regions.", trigger_when: "When a user request matches this analysis approach and its supported business context.", businessDomain: ["City Strategy", "4P"], metrics: ["Member conversion", "Campaign ROI"], output_requirements: "Start with an executive summary, then list evidence, prioritized opportunities, limitations and recommended actions.", analysis_constraints: "Do not infer causality from correlation or analyze dimensions without supporting data.", status: true },
    "scenario-channel-performance": { type: "Scenario Reporting", scenario_report_title: "Channel Performance Analysis", scenario_report_linked: "Invest City Strategy Analysis", scenario_report_description: "Channel efficiency, drivers and recommended actions", scenario_report_blueprint: "Summarize channel performance.", attachments: ["channel-report.pdf"] },
  },
};
