/** Default copy. Callers override any key through `strings`. */
export const DATA_MODEL_VIEW_STRINGS = {
  searchLabel: "Search data model",
  searchPlaceholder: "Search data model",
  basicTab: "Basic information",
  graphTab: "Relationship graph",
  synonymsLabel: "Synonyms",
  relatedReportsLabel: "Related reports",
  enabled: "Enabled",
  disabled: "Disabled",
  emptyDomains: "No matching data models.",
  tablesLabel: "Tables",
  none: "None",
  fact: "Fact",
  dimension: "Dimension",
  fieldDetails: "Field Details",
  dataPreview: "Data Preview",
  closeTable: "Close table detail",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  fitGraph: "Fit graph",
  fieldColumn: "Field",
  nameColumn: "Name",
  synonymsColumn: "Synonyms",
  unitColumn: "Unit",
  tabsAria: "Data model tabs",
  listAria: "Data models",
  graphToolsAria: "Relationship graph zoom controls",
  tableTabsAria: "Table detail tabs",
  relatedAria: (report) => `Open ${report} Report Context`,
};
