/** P12 Review Center source/runtime pairs; source fixture paths remain read-only. */
const url = "/assets/pages/review-center.html";
const story = (id, expect, actions = []) => ({ id: `pages--review-center${id ? `-${id}` : ""}`, expect, actions });
const seed = (items) => ({ pendingRestorations: JSON.stringify(items) });
const warning = { id: "restore-warning", title: "Restored validation item", summary: "Restoration awaiting governance review.", type: "Data Model", source: "Shared", submittedBy: "Current User", submitted: "Today", status: "pending", aiCheck: "Warning", warning: "Check the restored lineage before approval." };
const pass = { ...warning, id: "restore-pass", title: "Restored checked item", aiCheck: "Pass", warning: "" };
const plain = { ...warning, id: "restore-fallback", title: "Restored item without suggestions", aiCheck: "Reviewing", warning: "" };
export default [
  { id: "p12-default", original: { url, expect: [{ sel: ".review-tab.active", text: "Pending Review" }, { sel: ".asset-card", count: 6 }, { sel: "#pendingCount", text: "6" }, { sel: "#rejectedCount" }] }, story: story("", [{ sel: ".mh-review-page[data-review-tab='pending']" }, { sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 6 }, { sel: ".mh-review-page__stats article:first-child strong", text: "6" }, { sel: ".mh-review-page__stats article:last-child strong", text: "0" }, { sel: ".mh-library-toolbar [role='tab']", count: 3 }]) },
  { id: "p12-approved", original: { url, actions: [{ click: '.review-tab[data-tab="approved"]' }], expect: [{ sel: ".review-tab.active", text: "Approved" }, { sel: ".asset-card", count: 21 }] }, story: story("approved", [{ sel: ".mh-review-page[data-review-tab='approved']" }, { sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 21 }]) },
  { id: "p12-search", original: { url, actions: [{ fill: ["#reviewSearch", "Campaign ROI"] }], expect: [{ sel: ".asset-card", count: 1, text: "Campaign ROI" }] }, story: story("", [{ sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 1, text: "Campaign ROI" }, { sel: ".mh-library-toolbar__count", text: "1 item" }], [{ fill: [".mh-library-toolbar input[type='search']", "Campaign ROI"] }]) },
  { id: "p12-empty", original: { url, actions: [{ fill: ["#reviewSearch", "no matching review"] }], expect: [{ sel: "#reviewEmptyState:not([hidden])", text: "No matching items" }, { sel: ".asset-card", count: 0, state: "detached" }] }, story: story("empty", [{ sel: ".mh-review-page .mh-library-empty", text: "No matching items" }, { sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 0, state: "detached" }]) },
  { id: "p12-type", original: { url, actions: [{ select: ["#reviewTypeFilter", "Data Model"] }, { eval: "if (document.querySelector('#reviewTypeFilter').value !== 'Data Model') throw new Error('source type did not change')" }], expect: [{ sel: ".asset-card", count: 2 }, { sel: "#reviewTypeFilter" }] }, story: story("", [{ sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 2 }, { sel: '.mh-library-toolbar__facet:has-text("Type") select' }], [{ select: ['.mh-library-toolbar__facet:has-text("Type") select', "Data Model"] }, { eval: "if (document.querySelectorAll('.mh-library-toolbar__facet select')[0].value !== 'Data Model') throw new Error('story type did not change')" }]) },
  { id: "p12-time", original: { url, actions: [{ select: ["#reviewTimeFilter", "today"] }, { eval: "if (document.querySelector('#reviewTimeFilter').value !== 'today') throw new Error('source time did not change')" }], expect: [{ sel: "#reviewTimeFilter option:checked", state: "attached", text: "Today" }] }, story: story("", [{ sel: '.mh-library-toolbar__facet:has-text("Submitted") select' }, { sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 3 }, { sel: ".mh-library-toolbar__count", text: "3 items" }], [{ select: ['.mh-library-toolbar__facet:has-text("Submitted") select', "today"] }, { eval: "if (document.querySelectorAll('.mh-library-toolbar__facet select')[1].value !== 'today') throw new Error('story time did not change')" }]) },
  { id: "p12-pending-detail", original: { url, actions: [{ click: '.asset-card[data-id="pending-1"] .asset-title' }], expect: [{ sel: ".review-detail-panel.open", text: "Campaign investment decision principles" }, { sel: "#reviewDetailWarning:not([hidden])" }, { sel: "#reviewDetailAiSuggestions li", count: 3 }] }, story: story("pending-detail", [{ sel: ".mh-review-page__detail", text: "Campaign investment decision principles" }, { sel: ".mh-review-page__warning", text: "Warning" }, { sel: ".mh-review-page__detail .mh-review-page__suggestions li", count: 3 }]) },
  { id: "p12-pending-plain", original: { url, storage: seed([plain]), actions: [{ click: '.asset-card[data-id="restore-fallback"] .asset-title' }], expect: [{ sel: ".review-detail-panel.open", text: "Restored item without suggestions" }, { sel: "#reviewDetailWarning", state: "hidden" }, { sel: "#reviewDetailAiSection", state: "hidden" }] }, story: story("pending-plain", [{ sel: ".mh-review-page__detail", text: "Restored item without suggestions" }, { sel: ".mh-review-page__detail .mh-review-page__warning", count: 0, state: "detached" }, { sel: ".mh-review-page__detail .mh-review-page__suggestions", count: 0, state: "detached" }]) },
  { id: "p12-approved-detail", original: { url, actions: [{ click: '.review-tab[data-tab="approved"]' }, { click: '.asset-card[data-id="approved-1"] .review-btn.view' }], expect: [{ sel: ".review-detail-panel.open", text: "Trusted analysis guardrails" }, { sel: "#reviewDetailActions", text: "View in Knowledge Base" }] }, story: story("approved-detail", [{ sel: ".mh-review-page__detail", text: "Trusted analysis guardrails" }, { sel: ".mh-review-page__detail-actions", text: "View in Knowledge Base" }]) },
  { id: "p12-view-same-detail", original: { url, actions: [{ click: '.review-tab[data-tab="approved"]' }, { click: '.asset-card[data-id="approved-1"] .review-btn.view' }, { click: '#reviewDetailActions .review-btn.view' }], expect: [{ sel: ".review-detail-panel.open", text: "Trusted analysis guardrails" }, { sel: "#reviewDetailActions", text: "View in Knowledge Base" }] }, story: story("approved-detail", [{ sel: ".mh-review-page__detail", text: "Trusted analysis guardrails" }], [{ click: ".mh-review-page__detail-actions button" }]) },
  { id: "p12-reject", original: { url, actions: [{ click: '.asset-card[data-id="pending-1"] .review-btn.reject' }], expect: [{ sel: ".reject-panel.open", text: "Reject: Campaign investment decision principles" }, { sel: "#rejectAiContent li", count: 3 }] }, story: story("reject", [{ sel: ".mh-review-page__reject", text: "Reject: Campaign investment decision principles" }, { sel: ".mh-review-page__reject .mh-review-page__suggestions li", count: 3 }]) },
  { id: "p12-reject-typed", original: { url, actions: [{ click: '.asset-card[data-id="pending-1"] .review-btn.reject' }, { fill: ["#rejectReasonInput", "Needs current evidence."] }, { eval: "if (document.querySelector('#rejectReasonInput').value !== 'Needs current evidence.') throw new Error('reason did not update')" }], expect: [{ sel: ".reject-panel.open", text: "Campaign investment decision principles" }] }, story: story("reject", [{ sel: ".mh-review-page__reject", text: "Campaign investment decision principles" }], [{ fill: [".mh-review-page__reason textarea", "Needs current evidence."] }, { eval: "if (document.querySelector('.mh-review-page__reason textarea').value !== 'Needs current evidence.') throw new Error('reason did not update')" }]) },
  { id: "p12-reject-fallback", original: { url, storage: seed([plain]), actions: [{ click: '.asset-card[data-id="restore-fallback"] .review-btn.reject' }], expect: [{ sel: ".reject-panel.open", text: "Restored item without suggestions" }, { sel: "#rejectAiContent li", count: 2 }] }, story: story("reject-fallback", [{ sel: ".mh-review-page__reject", text: "Restored item without suggestions" }, { sel: ".mh-review-page__reject .mh-review-page__suggestions li", count: 2 }]) },
  { id: "p12-reject-empty-confirm", original: { url, actions: [{ click: '.asset-card[data-id="pending-1"] .review-btn.reject' }, { press: ["#rejectConfirmBtn", "Enter"] }], expect: [{ sel: ".asset-card", count: 5 }, { sel: "#pendingCount", text: "5" }, { sel: "#rejectedCount" }] }, story: story("", [{ sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 5 }, { sel: ".mh-review-page__stats article:first-child strong", text: "5" }, { sel: ".mh-review-page__stats article:last-child strong", text: "1" }, { sel: ".mh-library-toolbar [role='tab']:has-text(\"Rejected\")", text: "Rejected 1" }, { sel: ".mh-toast", text: "Rejected" }], [{ click: ".mh-review-page tbody tr:has-text(\"Campaign investment decision principles\") button:has-text(\"Reject\")" }, { click: ".mh-review-page__reject-actions button:last-child" }]) },
  { id: "p12-risk-reviewing", original: { url, actions: [{ click: '.asset-card[data-id="pending-3"] .review-btn.approve' }], expect: [{ sel: "#riskModal:not([hidden])", text: "AI Review In Progress" }, { sel: "#pendingCount", text: "6" }] }, story: story("risk-reviewing", [{ sel: ".mh-confirm", text: "AI Review In Progress" }, { sel: ".mh-review-page__stats article:first-child strong", text: "6" }]) },
  { id: "p12-risk-warning", original: { url, storage: seed([warning]), actions: [{ click: '.asset-card[data-id="restore-warning"] .review-btn.approve' }], expect: [{ sel: "#riskModal:not([hidden])", text: "AI Warning Detected" }, { sel: "#pendingCount", text: "7" }] }, story: story("risk-warning", [{ sel: ".mh-confirm", text: "AI Warning Detected" }, { sel: ".mh-review-page__stats article:first-child strong", text: "7" }]) },
  { id: "p12-risk-cancel", original: { url, actions: [{ click: '.asset-card[data-id="pending-3"] .review-btn.approve' }, { click: "#riskModalCancel" }], expect: [{ sel: "#riskModal", state: "hidden" }, { sel: ".asset-card", count: 6 }] }, story: story("risk-reviewing", [{ sel: ".mh-confirm", count: 0, state: "detached" }, { sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 6 }], [{ click: ".mh-confirm__btn:not(.mh-confirm__btn--primary)" }]) },
  { id: "p12-risk-approve", original: { url, actions: [{ click: '.asset-card[data-id="pending-3"] .review-btn.approve' }, { click: "#riskModalConfirm" }], expect: [{ sel: ".asset-card", count: 5 }, { sel: "#approvedCount", text: "22" }] }, story: story("risk-reviewing", [{ sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 5 }, { sel: ".mh-toast", text: "Approved" }, { sel: ".mh-review-page__stats article:nth-child(2) strong", text: "22" }], [{ click: ".mh-confirm__btn--primary" }]) },
  { id: "p12-pass-direct", original: { url, storage: seed([pass]), actions: [{ click: '.asset-card[data-id="restore-pass"] .review-btn.approve' }], expect: [{ sel: "#riskModal", state: "hidden" }, { sel: ".asset-card", count: 6 }, { sel: "#approvedCount", text: "22" }] }, story: story("direct-pass", [{ sel: ".mh-confirm", count: 0, state: "detached" }, { sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 6 }, { sel: ".mh-review-page__stats article:nth-child(2) strong", text: "22" }], [{ click: '.mh-review-page tbody tr:has-text("Restored checked item") button:has-text("Approve")' }]) },
  { id: "p12-assistant-open", original: { url, actions: [{ click: ".global-ai-launcher" }], expect: [{ sel: "#assistantPanel:not([hidden])", text: "Ask a question" }, { sel: ".global-ai-launcher", state: "hidden" }] }, story: story("assistant", [{ sel: ".mh-assistant", text: "Ask a question" }, { sel: ".mh-launcher", state: "hidden" }]) },
  { id: "p12-assistant-fill", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: ".ask-suggestion:first-child" }], expect: [{ sel: "#promptCanvas", text: "Definition of Attributed ROI" }, { sel: "#answerFeed .answer-card", count: 0, state: "detached" }] }, story: story("assistant-filled", [{ sel: ".mh-assistant__answer", count: 0, state: "detached" }], [{ eval: "(() => { const field = document.querySelector('.mh-assistant__box textarea'); if (!field?.value.includes('Definition of Attributed ROI')) throw new Error('filled story prompt missing'); })()" }]) },
  { id: "p12-assistant-fill-action", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: ".ask-suggestion:first-child" }], expect: [{ sel: "#promptCanvas", text: "Definition of Attributed ROI" }] }, story: story("assistant", [{ sel: ".mh-assistant__send button:not([disabled])", count: 1 }], [{ click: ".mh-assistant__suggestions button:first-child" }, { eval: "if (document.querySelector('.mh-assistant__box textarea').value !== 'Definition of Attributed ROI') throw new Error('suggestion click did not fill')" }]) },
  { id: "p12-assistant-answer", original: { url, actions: [{ click: ".global-ai-launcher" }, { fill: ["#promptCanvas", "Definition of Attributed ROI"] }, { click: "#sendQuery" }], expect: [{ sel: "#answerFeed .answer-card", text: "I will use the AI Interpreter knowledge context to answer:" }] }, story: story("assistant-answer", [{ sel: ".mh-assistant__answer--simple", text: "I will use the AI Interpreter knowledge context to answer:" }]) },
  { id: "p12-assistant-history", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#aiHistory" }], expect: [{ sel: "#aiRecentHistoryPopup:not([hidden])", text: "Summarize the latest media tracking performance." }] }, story: story("assistant-history", [{ sel: ".mh-assistant__history-pop", text: "Summarize the latest media tracking performance." }]) },
  { id: "p12-assistant-maximize", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#aiMaximize" }], expect: [{ sel: "#assistantPanel.is-ai-expanded", text: "Ask AI Interpreter" }] }, story: story("assistant-maximized", [{ sel: ".mh-assistant--expanded", text: "Ask AI Interpreter" }]) },
  { id: "p12-assistant-skill", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }], expect: [{ sel: "#aiSkillMenu:not([hidden])", text: "Analytical Model" }] }, story: story("assistant-skills", [{ sel: ".mh-skill", text: "Analytical Model" }]) },
  { id: "p12-assistant-model", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category >> nth=1" }, { wait: ".ai-skill-detail-panel:not([hidden])" }, { click: ".ai-skill-option:has-text('ROI diagnosis')" }], expect: [{ sel: ".ai-skill-chip:not([hidden])", text: "ROI diagnosis model" }] }, story: story("assistant-selected", [{ sel: ".mh-assistant__chip", text: "ROI diagnosis model" }]) },
  { id: "p12-model-history", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category >> nth=1" }, { click: "[data-ai-skill-action='history']" }], expect: [{ sel: ".ai-flow-dialog", text: "Generate Analytical Model" }] }, story: story("model-history", [{ sel: ".mh-flow", text: "Generate Analytical Model" }]) },
  { id: "p12-model-manual", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='manual']" }], expect: [{ sel: "#aiGeneratedModelDialog .ai-model-form-card", text: "Create Analytical Model Manually" }, { sel: "#aiGeneratedModelDialog [data-ai-required='Name']" }] }, story: story("model-manual", [{ sel: ".mh-flow__card--form", text: "Create Analytical Model Manually" }, { sel: ".mh-flow input[name='name']" }]) },
  { id: "p12-model-generated", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='history']" }, { click: "[data-ai-generate-model]" }], expect: [{ sel: "#aiGeneratedModelDialog .ai-model-form-card", text: "New Analytical Model" }, { sel: "#aiGeneratedModelDialog [data-ai-required='Name']" }] }, story: story("model-generated", [{ sel: ".mh-flow__card--form", text: "New Analytical Model" }, { sel: ".mh-flow input[name='name']" }]) },
  { id: "p12-model-required", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='manual']" }, { click: "[data-ai-submit-model]" }], expect: [{ sel: "#aiGeneratedModelDialog .field-error", count: 3, text: "is required" }] }, story: story("model-error", [{ sel: ".mh-flow__field-error", count: 3, text: "is required" }]) },
  { id: "p12-model-empty-selection", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='history']" }, { eval: "document.querySelectorAll('#aiHistoryGenerateDialog [data-ai-history-msg]:checked').forEach(el => el.click())" }, { click: "[data-ai-generate-model]" }], expect: [{ sel: "[data-ai-generate-error]:not([hidden])", text: "Select at least one message to continue." }] }, story: story("model-empty", [{ sel: ".mh-flow__error", text: "Select at least one message to continue." }]) },
  { id: "p12-model-save-complete", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='manual']" }, { fill: ["#aiGeneratedModelDialog [data-ai-required='Name']", "Weekly report diagnosis"] }, { fill: ["#aiGeneratedModelDialog [data-ai-required='Trigger When']", "When report metrics move"] }, { fill: ["#aiGeneratedModelDialog [data-ai-required='Structure & Guidance']", "Compare and explain"] }, { click: "[data-ai-save-model]" }, { waitMs: 550 }], expect: [{ sel: "#aiGeneratedModelDialog", state: "detached" }, { sel: "#assistantPanel:not([hidden])", text: "Ask AI Interpreter" }] }, story: story("model-manual", [{ sel: ".mh-flow", state: "detached" }, { sel: ".mh-assistant", text: "Ask AI Interpreter" }], [{ fill: [".mh-flow input[name='name']", "Weekly report diagnosis"] }, { fill: [".mh-flow textarea[name='trigger']", "When report metrics move"] }, { fill: [".mh-flow textarea[name='structure']", "Compare and explain"] }, { click: ".mh-flow__foot .mh-flow__btn--secondary:has-text('Save')" }, { waitMs: 550 }]) },

  { id: "p12-assistant-history-fill", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#aiHistory" }, { click: "#aiRecentHistoryPopup .ai-recent-chat" }, { eval: "if (document.querySelector('#promptCanvas').textContent !== 'Summarize the latest media tracking performance.') throw new Error('source history did not fill')" }], expect: [{ sel: "#sendQuery:not([disabled])", count: 1 }, { sel: "#answerFeed .answer-card", count: 0, state: "detached" }] }, story: story("assistant", [{ sel: ".mh-assistant__send button:not([disabled])", count: 1 }, { sel: ".mh-assistant__answer", count: 0, state: "detached" }], [{ click: ".mh-assistant__history .mh-assistant__icon" }, { click: ".mh-assistant__history-item:first-child" }, { eval: "if (document.querySelector('.mh-assistant__box textarea').value !== 'Summarize the latest media tracking performance.') throw new Error('story history did not fill')" }]) },
  { id: "p12-assistant-new-session", original: { url, actions: [{ click: ".global-ai-launcher" }, { fill: ["#promptCanvas", "Definition of Attributed ROI"] }, { click: "#sendQuery" }, { click: "#aiNewSession" }], expect: [{ sel: "#answerFeed", state: "hidden" }, { sel: ".assistant-ask-stage", text: "Ask a question" }, { sel: "#sendQuery[disabled]" }] }, story: story("assistant-answer", [{ sel: ".mh-assistant__answer", count: 0, state: "detached" }, { sel: ".mh-assistant__stage", text: "Ask a question" }, { sel: ".mh-assistant__send button[disabled]" }], [{ click: "button[aria-label='New session']" }]) },
  { id: "p12-assistant-skill-search", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { fill: [".ai-skill-search input", "no matching model"] }], expect: [{ sel: ".ai-skill-empty", text: "No matching skills" }, { sel: ".ai-skill-detail-panel:not([hidden])" }] }, story: story("assistant-skill-search", [{ sel: ".mh-skill__empty", text: "No matching skills" }, { sel: ".mh-skill__detail" }]) },
  { id: "p12-assistant-skill-clear", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: ".ai-skill-option:has-text('ROI diagnosis')" }, { click: ".ai-skill-chip button" }], expect: [{ sel: ".ai-skill-chip", state: "hidden" }, { sel: "#promptCanvas", attr: { name: "aria-label", value: "Ask AI Interpreter AI" } }] }, story: story("assistant-selected", [{ sel: ".mh-assistant__chip", count: 0, state: "detached" }, { sel: ".mh-assistant__box textarea", attr: { name: "aria-label", value: "Ask AI Interpreter AI" } }], [{ click: ".mh-assistant__chip button" }]) },
  { id: "p12-assistant-enter-keeps-prompt", original: { url, actions: [{ click: ".global-ai-launcher" }, { fill: ["#promptCanvas", "Line one"] }, { press: ["#promptCanvas", "Enter"] }, { eval: "if (!document.querySelector('#promptCanvas').textContent.includes('Line one')) throw new Error('source prompt lost')" }], expect: [{ sel: "#answerFeed .answer-card", count: 0, state: "detached" }, { sel: "#sendQuery:not([disabled])", count: 1 }] }, story: story("assistant", [{ sel: ".mh-assistant__answer", count: 0, state: "detached" }, { sel: ".mh-assistant__send button:not([disabled])", count: 1 }], [{ fill: [".mh-assistant__box textarea", "Line one"] }, { press: [".mh-assistant__box textarea", "Enter"] }, { eval: "if (!document.querySelector('.mh-assistant__box textarea').value.includes('Line one')) throw new Error('story prompt lost')" }]) },
  { id: "p12-assistant-scrim", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#assistantPanel .panel-backdrop" }], expect: [{ sel: "#assistantPanel[hidden]", state: "attached" }, { sel: ".global-ai-launcher", text: "AI Interpreter" }] }, story: story("assistant", [{ sel: ".mh-assistant", count: 0, state: "detached" }, { sel: ".mh-launcher", text: "AI Interpreter" }], [{ click: ".mh-assistant__backdrop" }]) },
  { id: "p12-assistant-escape", original: { url, actions: [{ click: ".global-ai-launcher" }, { press: ["body", "Escape"] }], expect: [{ sel: "#assistantPanel[hidden]", state: "attached" }, { sel: ".global-ai-launcher", text: "AI Interpreter" }] }, story: story("assistant", [{ sel: ".mh-assistant", count: 0, state: "detached" }, { sel: ".mh-launcher", text: "AI Interpreter" }], [{ press: ["body", "Escape"] }]) },
  { id: "p12-model-submit-complete", original: { url, actions: [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='manual']" }, { fill: ["#aiGeneratedModelDialog [data-ai-required='Name']", "Weekly report diagnosis"] }, { fill: ["#aiGeneratedModelDialog [data-ai-required='Trigger When']", "When report metrics move"] }, { fill: ["#aiGeneratedModelDialog [data-ai-required='Structure & Guidance']", "Compare and explain"] }, { click: "[data-ai-submit-model]" }, { waitMs: 550 }], expect: [{ sel: "#aiGeneratedModelDialog", state: "detached" }, { sel: "#assistantPanel:not([hidden])", text: "Ask AI Interpreter" }] }, story: story("model-manual", [{ sel: ".mh-flow", count: 0, state: "detached" }, { sel: ".mh-assistant", text: "Ask AI Interpreter" }], [{ fill: [".mh-flow input[name='name']", "Weekly report diagnosis"] }, { fill: [".mh-flow textarea[name='trigger']", "When report metrics move"] }, { fill: [".mh-flow textarea[name='structure']", "Compare and explain"] }, { click: ".mh-flow__foot .mh-flow__btn--primary:has-text('Submit')" }, { waitMs: 550 }]) },

  { id: "p12-approved-bottom", original: { url, actions: [{ click: '.review-tab[data-tab="approved"]' }, { eval: "window.scrollTo(0, document.body.scrollHeight)" }, { waitMs: 250 }, { eval: "if (document.querySelector('.asset-card:last-child').getBoundingClientRect().top >= innerHeight) throw new Error('source last approved row not reached')" }], expect: [{ sel: ".asset-card", count: 21 }, { sel: ".asset-card:last-child", text: "Morning performance routine" }] }, story: story("approved", [{ sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 21 }, { sel: ".mh-review-page tbody tr:last-child", text: "Morning performance routine" }], [{ eval: "window.scrollTo(0, document.body.scrollHeight)" }, { waitMs: 250 }, { eval: "if (document.querySelector('.mh-review-page tbody tr:last-child').getBoundingClientRect().top >= innerHeight) throw new Error('story last approved row not reached')" }]) },
  { id: "p12-narrow-queue", viewport: { width: 390, height: 844 }, original: { url, expect: [{ sel: ".asset-card", count: 6 }, { sel: '.asset-card[data-id="pending-1"] .asset-title', text: "Campaign investment decision principles" }] }, story: story("", [{ sel: ".mh-review-page tbody tr:not(.mh-table__empty-row)", count: 6 }, { sel: '.mh-review-page tbody tr:first-child .mh-table__open', text: "Campaign investment decision principles" }]) },

];
