/** P14 Personal Memory: source-reachable workspace states and shared lite assistant. */
import p12 from "./p12.mjs";

const url = "/assets/pages/personal-memory.html";
const story = (id, expect, actions = []) => ({ id: `pages--personal-memory${id ? `-${id}` : ""}`, expect, actions });
const card = (id) => `.memory-card[data-id="${id}"]`;
const menuDelete = (id) => [{ click: `${card(id)} .memory-card-more` }, { click: `${card(id)} .memory-card-dropdown-item.delete` }];
const sourceStates = [
  { id: "p14-default", original: { url, expect: [{ sel: ".memory-card", count: 18 }, { sel: ".memory-ai-banner", text: "AI-powered Memory Assistant" }, { sel: "#memoryDetailEmpty:not([hidden])", text: "Select a memory" }] }, story: story("", [{ sel: ".mh-library-item", count: 18 }, { sel: ".mh-memory-page__banner", text: "AI-powered Memory Assistant" }, { sel: ".mh-memory-workspace__empty-detail", text: "Select a memory" }]) },
  { id: "p14-analysis", original: { url, actions: [{ click: '.memory-category-tab[data-category="analysis"]' }], expect: [{ sel: ".memory-card", count: 6 }, { sel: ".memory-category-tab.active", text: "Analysis Preference" }] }, story: story("category", [{ sel: ".mh-library-item", count: 6 }, { sel: '.mh-memory-page[data-memory-category="analysis"]' }]) },
  { id: "p14-empty", original: { url, actions: [{ click: '.memory-category-tab[data-category="reference"]' }, ...menuDelete("mem-reference-1"), { click: "#deleteConfirmBtn" }, ...menuDelete("mem-reference-2"), { click: "#deleteConfirmBtn" }, ...menuDelete("mem-reference-3"), { click: "#deleteConfirmBtn" }], expect: [{ sel: ".memory-empty-state", text: "No memories in this category" }, { sel: ".memory-card", count: 0, state: "detached" }] }, story: story("empty", [{ sel: ".mh-library-empty", text: "No memories in this category" }, { sel: ".mh-library-item", count: 0, state: "detached" }]) },
  { id: "p14-banner-close", original: { url, actions: [{ click: ".memory-ai-banner-close" }], expect: [{ sel: "#memoryAiBanner", state: "hidden" }, { sel: ".memory-card", count: 18 }] }, story: story("banner-closed", [{ sel: ".mh-memory-page__banner", count: 0, state: "detached" }, { sel: ".mh-library-item", count: 18 }]) },
  { id: "p14-detail", original: { url, actions: [{ click: `${card("mem-analysis-1")} .memory-card-body` }], expect: [{ sel: "#memoryDetailContent:not([hidden])", text: "City conversion funnel drop" }, { sel: "#memoryDetailDescription", text: "Shanghai and Beijing" }] }, story: story("detail", [{ sel: ".mh-memory-workspace__detail h3", text: "City conversion funnel drop" }, { sel: ".mh-memory-workspace__detail p", text: "Shanghai and Beijing" }]) },
  { id: "p14-edit", original: { url, actions: [{ click: `${card("mem-analysis-1")} .memory-card-body` }, { click: "#memoryEditBtn" }], expect: [{ sel: "#editTitle", count: 1 }, { sel: "#editDescription", count: 1 }] }, story: story("edit", [{ sel: ".mh-memory-workspace__field input", count: 1 }, { sel: ".mh-memory-workspace__field textarea", count: 1 }], [{ eval: "if (!document.querySelector('.mh-memory-workspace__field input').value.includes('City conversion')) throw new Error('edit draft missing source title')" }]) },
  { id: "p14-edit-save", original: { url, actions: [{ click: `${card("mem-analysis-1")} .memory-card-body` }, { click: "#memoryEditBtn" }, { fill: ["#editTitle", "Edited city memory"] }, { click: "#editSaveBtn" }], expect: [{ sel: "#memoryDetailTitle", text: "Edited city memory" }, { sel: ".memory-card.active .memory-card-title", text: "Edited city memory" }] }, story: story("detail", [{ sel: ".mh-memory-workspace__detail h3", text: "Edited city memory" }, { sel: '.mh-library-item--selected .mh-library-item__title', text: "Edited city memory" }], [{ click: ".mh-memory-workspace__actions button:has-text('Edit')" }, { fill: [".mh-memory-workspace__field input", "Edited city memory"] }, { click: ".mh-memory-workspace__actions button:has-text('Save Changes')" }]) },
  { id: "p14-create", original: { url, actions: [{ click: "#newMemoryBtn" }], expect: [{ sel: "#createMemoryPanel.open", text: "Create a new personal memory" }, { sel: "#createMemoryTitle" }, { sel: "#createMemoryDescription" }] }, story: story("create", [{ sel: ".mh-memory-page__create", text: "Create a new personal memory" }, { sel: ".mh-memory-page__form input" }, { sel: ".mh-memory-page__form textarea" }]) },
  { id: "p14-create-errors", original: { url, actions: [{ click: "#newMemoryBtn" }, { press: ["#createMemorySave", "Enter"] }], expect: [{ sel: ".field-error-msg:not([hidden])", count: 2, text: "Cannot be empty" }] }, story: story("create-errors", [{ sel: ".mh-memory-page__form small", count: 2, text: "CANNOT BE EMPTY" }, { sel: '.mh-memory-page__form [aria-invalid="true"]', count: 2 }]) },
  { id: "p14-cross-category", original: { url, actions: [{ click: '.memory-category-tab[data-category="reference"]' }, { click: "#newMemoryBtn" }, { fill: ["#createMemoryTitle", "Cross-category analysis"] }, { fill: ["#createMemoryDescription", "New analysis while Others remains selected."] }, { press: ["#createMemorySave", "Enter"] }], expect: [{ sel: ".memory-card", count: 3 }, { sel: "#memoryDetailTitle", text: "Cross-category analysis" }, { sel: ".memory-category-tab.active", text: "Others" }] }, story: story("cross-category", [{ sel: ".mh-library-item", count: 3 }, { sel: ".mh-memory-workspace__detail h3", text: "Cross-category analysis" }, { sel: '.mh-memory-page[data-memory-category="reference"]' }]) },
  { id: "p14-delete-confirm", original: { url, actions: [{ click: `${card("mem-analysis-1")} .memory-card-body` }, ...menuDelete("mem-meeting-1")], expect: [{ sel: "#memoryDeleteOverlay.open", text: "Weekly marketing standup" }, { sel: "#memoryDetailTitle", text: "City conversion funnel drop" }] }, story: story("delete-confirm", [{ sel: ".mh-confirm", text: "Weekly marketing standup" }, { sel: ".mh-memory-workspace__detail h3", text: "City conversion funnel drop" }]) },
  { id: "p14-delete-done", original: { url, actions: [...menuDelete("mem-meeting-1"), { click: "#deleteConfirmBtn" }], expect: [{ sel: ".memory-card", count: 17 }, { sel: "#memoryDeleteOverlay.open", count: 0, state: "detached" }] }, story: story("", [{ sel: ".mh-library-item", count: 17 }, { sel: ".mh-confirm", count: 0, state: "detached" }, { sel: ".mh-toast", text: "Deleted successfully" }], [{ click: '.mh-library-item:has-text("Weekly marketing standup") .mh-item-actions__button--danger' }, { click: ".mh-confirm__btn--primary" }]) },
  { id: "p14-autofill", original: { url, actions: [{ click: "#newMemoryBtn" }], expect: [{ sel: "#createMemoryPanel.open .create-memory-ai-fill", text: "AI Auto-fill" }] }, story: story("create", [{ sel: ".mh-memory-page__form textarea:not(:placeholder-shown)", count: 1 }], [{ click: ".mh-autofill button" }]) },
  { id: "p14-bottom", original: { url, actions: [{ eval: "window.scrollTo(0,document.body.scrollHeight)" }, { waitMs: 200 }], expect: [{ sel: ".memory-card", count: 18 }, { sel: '.memory-card[data-id="mem-reference-3"]', text: "Approved vendor list" }] }, story: story("", [{ sel: ".mh-library-item", count: 18 }, { sel: '.mh-library-item:has-text("Approved vendor list")', text: "Approved vendor list" }], [{ eval: "window.scrollTo(0,document.body.scrollHeight)" }, { waitMs: 200 }]) },
  { id: "p14-narrow", viewport: { width: 390, height: 844 }, original: { url, expect: [{ sel: ".memory-card", count: 18 }, { sel: ".memory-ai-banner", text: "AI-powered Memory Assistant" }] }, story: story("", [{ sel: ".mh-library-item", count: 18 }, { sel: ".mh-memory-page__banner", text: "AI-powered Memory Assistant" }]) },
];

const assistantStates = p12.filter((item) => item.id.startsWith("p12-assistant-") || item.id.startsWith("p12-model-")).map((item) => ({ ...item, id: item.id.replace(/^p12-/, "p14-"), original: { ...item.original, url }, story: { ...item.story, id: item.story.id.replace("pages--review-center", "pages--personal-memory") } }));

export default [...sourceStates, ...assistantStates];
