/** P15 Skill Library: real source-reachable states and corrected propagation defect. */
const url = "/assets/pages/scenario-library.html";
const story = (suffix = "", expect = [], actions = []) => ({ id: `pages--scenario-library${suffix ? `-${suffix}` : ""}`, expect, actions });
const srcRows = [{ sel: ".scenario-row", count: 9 }, { sel: "#allTabCount", text: "9" }];
const reactRows = [{ sel: ".mh-skill-library__row", count: 9 }, { sel: ".mh-skill-library__tabs span", text: "9" }];

export default [
  { id: "p15-default", original: { url, expect: srcRows }, story: story("", reactRows) },
  { id: "p15-bottom", original: { url, actions: [{ eval: "window.scrollTo(0, document.body.scrollHeight)" }], expect: [{ sel: ".scenario-row", count: 9 }, { sel: ".scenario-row:last-child", text: "Competitive Media Analysis" }] }, story: story("", [{ sel: ".mh-skill-library__row", count: 9 }, { sel: ".mh-skill-library__row:last-child", text: "Competitive Media Analysis" }], [{ eval: "window.scrollTo(0, document.body.scrollHeight)" }]) },
  { id: "p15-owner-search", original: { url, actions: [{ fill: ["#scenarioSearch", "Emily Wang"] }], expect: [{ sel: ".scenario-row", count: 2 }, { sel: ".scenario-row:first-child", text: "Channel Performance Analysis" }] }, story: story("owner-search", [{ sel: ".mh-skill-library__row", count: 2 }, { sel: ".mh-skill-library__row:first-child", text: "Channel Performance Analysis" }]) },
  { id: "p15-draft", original: { url, actions: [{ select: ["#statusFilter", "Draft"] }], expect: [{ sel: ".scenario-row", count: 1 }, { sel: ".scenario-row", text: "Competitive Media Analysis" }] }, story: story("draft", [{ sel: ".mh-skill-library__row", count: 1 }, { sel: ".mh-skill-library__row", text: "Competitive Media Analysis" }]) },
  { id: "p15-review", original: { url, actions: [{ select: ["#statusFilter", "Under Review"] }], expect: [{ sel: ".scenario-row", count: 1 }, { sel: ".scenario-row", text: "Customer Funnel Optimization" }] }, story: story("review", [{ sel: ".mh-skill-library__row", count: 1 }, { sel: ".mh-skill-library__row", text: "Customer Funnel Optimization" }]) },
  { id: "p15-development", original: { url, actions: [{ select: ["#statusFilter", "In Development"] }], expect: [{ sel: ".scenario-row", count: 3 }, { sel: ".scenario-row:first-child", text: "Channel Performance Analysis" }] }, story: story("development", [{ sel: ".mh-skill-library__row", count: 3 }, { sel: ".mh-skill-library__row:first-child", text: "Channel Performance Analysis" }]) },
  { id: "p15-published", original: { url, actions: [{ select: ["#statusFilter", "Published"] }], expect: [{ sel: ".scenario-row", count: 4 }, { sel: ".scenario-row:first-child", text: "Campaign Review Reporting" }] }, story: story("published", [{ sel: ".mh-skill-library__row", count: 4 }, { sel: ".mh-skill-library__row:first-child", text: "Campaign Review Reporting" }]) },
  { id: "p15-empty", original: { url, actions: [{ fill: ["#scenarioSearch", "no matching scenario"] }], expect: [{ sel: "#emptyState:not([hidden])", text: "No matching scenarios" }, { sel: ".scenario-row", count: 0, state: "detached" }] }, story: story("empty", [{ sel: ".mh-skill-library__empty", text: "No matching scenarios" }, { sel: ".mh-skill-library__row", count: 0, state: "detached" }]) },
  { id: "p15-detail", original: { url, actions: [{ click: '.scenario-row:first-child' }], expect: [{ sel: ".scenario-detail-drawer.open", text: "Channel Performance Analysis" }, { sel: "#detailWhen", text: "When" }, { sel: "#detailUsageText", text: "Reports" }] }, story: story("detail", [{ sel: ".mh-skill-detail", text: "Channel Performance Analysis" }, { sel: ".mh-skill-detail__structure-item", count: 5 }, { sel: ".mh-skill-detail__usage", text: "Reports" }]) },
  { id: "p15-draft-detail", original: { url, actions: [{ click: '.scenario-row:last-child' }], expect: [{ sel: ".scenario-detail-drawer.open", text: "Competitive Media Analysis" }, { sel: "#detailReviewStatus", text: "Draft" }] }, story: story("draft-detail", [{ sel: ".mh-skill-detail", text: "Competitive Media Analysis" }, { sel: ".mh-skill-detail__governance", text: "Draft" }]) },
  { id: "p15-preview", original: { url, actions: [{ click: '.scenario-row:first-child' }, { click: "#previewToggle" }], expect: [{ sel: "#previewContent:not([hidden])", text: "EXAMPLE QUESTION" }, { sel: "#previewToggle", text: "Hide Preview" }] }, story: story("preview", [{ sel: ".mh-skill-detail__preview-body", text: "EXAMPLE QUESTION" }, { sel: ".mh-skill-detail__preview-head button", text: "Hide Preview" }]) },
  { id: "p15-detail-escape", original: { url, actions: [{ click: '.scenario-row:first-child' }, { press: ["body", "Escape"] }], expect: [{ sel: ".scenario-detail-drawer:not(.open)", attr: { name: "aria-hidden", value: "true" } }] }, story: story("detail", [{ sel: ".mh-skill-detail", count: 0, state: "detached" }, { sel: ".mh-skill-library__row", count: 9 }], [{ press: ["body", "Escape"] }]) },
  { id: "p15-create", original: { url, actions: [{ click: "#createNewScenarioBtn" }], expect: [{ sel: "#scenarioEditView:not([hidden])", text: "Scenario Configuration" }, { sel: ".scenario-edit-structure-item", count: 5 }] }, story: story("create", [{ sel: ".mh-skill-form", text: "Scenario Configuration" }, { sel: ".mh-skill-form__structure-item", count: 5 }]) },
  { id: "p15-edit", original: { url, actions: [{ click: '.scenario-row:first-child' }, { click: "#detailEditBtn" }, { eval: "document.querySelector('#scenarioName').setAttribute('data-value', document.querySelector('#scenarioName').value);document.querySelector('#scenarioScope').setAttribute('data-value', document.querySelector('#scenarioScope').value)" }], expect: [{ sel: "#scenarioEditView:not([hidden])", text: "Scenario Configuration" }, { sel: "#scenarioName", attr: { name: "data-value", value: "Channel Performance Analysis" } }, { sel: "#scenarioScope", attr: { name: "data-value", value: "" } }] }, story: story("edit", [{ sel: ".mh-skill-form", text: "Scenario Configuration" }, { sel: ".mh-skill-form__field input", attr: { name: "value", value: "Channel Performance Analysis" } }, { sel: ".mh-skill-form__field select", attr: { name: "data-value", value: "D2C Insights" } }], [{ eval: "document.querySelector('.mh-skill-form__field select').setAttribute('data-value', document.querySelector('.mh-skill-form__field select').value)" }]) },
  { id: "p15-status-corrected", original: { url, actions: [{ select: ["#statusFilter", "Under Review"] }, { click: '.scenario-row .scenario-status' }], expect: [{ sel: "#emptyState:not([hidden])", text: "No matching scenarios" }, { sel: ".scenario-detail-drawer.open", text: "Customer Funnel Optimization" }] }, story: story("status-review-advanced", [{ sel: ".mh-skill-library__empty", text: "No matching scenarios" }, { sel: ".mh-skill-detail", count: 0, state: "detached" }], [{ wait: ".mh-skill-library__empty" }]) },
  { id: "p15-development-advance", original: { url, actions: [{ select: ["#statusFilter", "In Development"] }, { click: '.scenario-row[data-index="2"] .scenario-status' }], expect: [{ sel: ".scenario-row", count: 2 }, { sel: ".scenario-detail-drawer.open", text: "City Comparison Analysis" }] }, story: story("status-development-advanced", [{ sel: ".mh-skill-library__row", count: 2 }, { sel: ".mh-skill-detail", count: 0, state: "detached" }], [{ wait: ".mh-skill-library__list:not(:has([data-skill-id=city-comparison]))" }]) },
  // The play function traverses Edit → Cancel → Create; wait for Create before checking the live input value.
  { id: "p15-create-after-edit", original: { url, actions: [{ click: '.scenario-row:first-child' }, { click: "#detailEditBtn" }, { click: "#cancelEditBtn" }, { click: "#createNewScenarioBtn" }, { eval: "document.querySelector('#scenarioName').setAttribute('data-value', document.querySelector('#scenarioName').value)" }], expect: [{ sel: "#scenarioEditView:not([hidden])", text: "Scenario Configuration" }, { sel: "#scenarioName", attr: { name: "data-value", value: "Channel Performance Analysis" } }] }, story: story("create-after-edit", [{ sel: ".mh-skill-form", text: "Scenario Configuration" }, { sel: ".mh-skill-form__field input", attr: { name: "data-value", value: "" } }], [{ wait: '.mh-skill-page[data-skill-mode="create"]' }, { eval: "document.querySelector('.mh-skill-form__field input').setAttribute('data-value', document.querySelector('.mh-skill-form__field input').value)" }]) },
  { id: "p15-blank-submit", original: { url, actions: [{ click: "#createNewScenarioBtn" }, { click: '.scenario-edit-form .scenario-edit-btn.primary' }], expect: [{ sel: "#scenarioEditView[hidden]", state: "attached", attr: { name: "hidden", value: "" } }, { sel: ".scenario-row", count: 9 }] }, story: story("blank-submit", [{ sel: ".mh-skill-form", count: 0, state: "detached" }, { sel: ".mh-skill-library__row", count: 9 }], [{ wait: ".mh-skill-library__row" }]) },
  { id: "p15-assistant", original: { url, actions: [{ click: ".global-ai-launcher" }], expect: [{ sel: "#assistantPanel:not([hidden])", text: "Ask AI Interpreter" }] }, story: story("assistant", [{ sel: ".mh-assistant", text: "Ask AI Interpreter" }, { sel: ".mh-launcher", count: 1, state: "hidden" }]) },
];
