/** P15 Skill Library: source-reachable states on the governed-library table (WP7h). */
const url = "/assets/pages/scenario-library.html";
const story = (suffix = "", expect = [], actions = []) => ({ id: `pages--scenario-library${suffix ? `-${suffix}` : ""}`, expect, actions });
const srcRows = [{ sel: ".scenario-row", count: 9 }, { sel: "#allTabCount", text: "9" }];
const ROW = ".mh-skill-page tbody tr";
const STATUS = '.mh-library-toolbar__facet:has-text("Status") select';
const reactRows = [{ sel: ROW, count: 9 }, { sel: ".mh-library-toolbar__count", text: "9 scenarios" }];

export default [
  { id: "p15-default", original: { url, expect: srcRows }, story: story("", reactRows) },
  { id: "p15-bottom", original: { url, actions: [{ eval: "window.scrollTo(0, document.body.scrollHeight)" }], expect: [{ sel: ".scenario-row", count: 9 }, { sel: ".scenario-row:last-child", text: "Competitive Media Analysis" }] }, story: story("", [{ sel: ROW, count: 9 }, { sel: ".mh-skill-page tbody tr:last-child", text: "Competitive Media Analysis" }], [{ eval: "window.scrollTo(0, document.body.scrollHeight)" }]) },
  { id: "p15-owner-search", original: { url, actions: [{ fill: ["#scenarioSearch", "Emily Wang"] }], expect: [{ sel: ".scenario-row", count: 2 }, { sel: ".scenario-row:first-child", text: "Channel Performance Analysis" }] }, story: story("owner-search", [{ sel: ROW, count: 2 }, { sel: ".mh-skill-page tbody tr:first-child", text: "Channel Performance Analysis" }]) },
  { id: "p15-draft", original: { url, actions: [{ select: ["#statusFilter", "Draft"] }], expect: [{ sel: ".scenario-row", count: 1 }, { sel: ".scenario-row", text: "Competitive Media Analysis" }] }, story: story("", [{ sel: ROW, count: 1 }, { sel: ROW, text: "Competitive Media Analysis" }], [{ select: [STATUS, "Draft"] }]) },
  { id: "p15-review", original: { url, actions: [{ select: ["#statusFilter", "Under Review"] }], expect: [{ sel: ".scenario-row", count: 1 }, { sel: ".scenario-row", text: "Customer Funnel Optimization" }] }, story: story("", [{ sel: ROW, count: 1 }, { sel: ROW, text: "Customer Funnel Optimization" }], [{ select: [STATUS, "Under Review"] }]) },
  { id: "p15-development", original: { url, actions: [{ select: ["#statusFilter", "In Development"] }], expect: [{ sel: ".scenario-row", count: 3 }, { sel: ".scenario-row:first-child", text: "Channel Performance Analysis" }] }, story: story("", [{ sel: ROW, count: 3 }, { sel: ".mh-skill-page tbody tr:first-child", text: "Channel Performance Analysis" }], [{ select: [STATUS, "In Development"] }]) },
  { id: "p15-published", original: { url, actions: [{ select: ["#statusFilter", "Published"] }], expect: [{ sel: ".scenario-row", count: 4 }, { sel: ".scenario-row:first-child", text: "Campaign Review Reporting" }] }, story: story("", [{ sel: ROW, count: 4 }, { sel: ".mh-skill-page tbody tr:first-child", text: "Campaign Review Reporting" }], [{ select: [STATUS, "Published"] }]) },
  { id: "p15-empty", original: { url, actions: [{ fill: ["#scenarioSearch", "no matching scenario"] }], expect: [{ sel: "#emptyState:not([hidden])", text: "No matching scenarios" }, { sel: ".scenario-row", count: 0, state: "detached" }] }, story: story("empty", [{ sel: ".mh-library-empty", text: "No matching scenarios" }, { sel: ROW, count: 0, state: "detached" }]) },
  { id: "p15-detail", original: { url, actions: [{ click: '.scenario-row:first-child' }], expect: [{ sel: ".scenario-detail-drawer.open", text: "Channel Performance Analysis" }, { sel: "#detailWhen", text: "When" }, { sel: "#detailUsageText", text: "Reports" }] }, story: story("detail", [{ sel: ".mh-skill-detail", text: "Channel Performance Analysis" }, { sel: ".mh-skill-detail .mh-scenario-structure__item", count: 5 }, { sel: ".mh-skill-detail__usage", text: "Reports" }]) },
  { id: "p15-draft-detail", original: { url, actions: [{ click: '.scenario-row:last-child' }], expect: [{ sel: ".scenario-detail-drawer.open", text: "Competitive Media Analysis" }, { sel: "#detailReviewStatus", text: "Draft" }] }, story: story("draft-detail", [{ sel: ".mh-skill-detail", text: "Competitive Media Analysis" }, { sel: ".mh-skill-detail__governance", text: "Draft" }]) },
  { id: "p15-preview", original: { url, actions: [{ click: '.scenario-row:first-child' }, { click: "#previewToggle" }], expect: [{ sel: "#previewContent:not([hidden])", text: "EXAMPLE QUESTION" }, { sel: "#previewToggle", text: "Hide Preview" }] }, story: story("preview", [{ sel: ".mh-skill-detail .mh-scenario-preview__body", text: "EXAMPLE QUESTION" }, { sel: ".mh-skill-detail .mh-scenario-preview button[aria-expanded='true']", text: "Hide Preview" }]) },
  { id: "p15-detail-escape", original: { url, actions: [{ click: '.scenario-row:first-child' }, { press: ["body", "Escape"] }], expect: [{ sel: ".scenario-detail-drawer:not(.open)", attr: { name: "aria-hidden", value: "true" } }] }, story: story("detail", [{ sel: ".mh-skill-detail", count: 0, state: "detached" }, { sel: ROW, count: 9 }], [{ press: ["body", "Escape"] }]) },
  { id: "p15-create", original: { url, actions: [{ click: "#createNewScenarioBtn" }], expect: [{ sel: "#scenarioEditView:not([hidden])", text: "Scenario Configuration" }, { sel: ".scenario-edit-structure-item", count: 5 }] }, story: story("create", [{ sel: ".mh-skill-form", text: "Scenario Configuration" }, { sel: ".mh-skill-form__card", count: 5 }]) },
  { id: "p15-edit", original: { url, actions: [{ click: '.scenario-row:first-child' }, { click: "#detailEditBtn" }, { eval: "document.querySelector('#scenarioName').setAttribute('data-value', document.querySelector('#scenarioName').value);document.querySelector('#scenarioScope').setAttribute('data-value', document.querySelector('#scenarioScope').value)" }], expect: [{ sel: "#scenarioEditView:not([hidden])", text: "Scenario Configuration" }, { sel: "#scenarioName", attr: { name: "data-value", value: "Channel Performance Analysis" } }, { sel: "#scenarioScope", attr: { name: "data-value", value: "" } }] }, story: story("edit", [{ sel: ".mh-skill-form", text: "Scenario Configuration" }, { sel: ".mh-skill-form__field input", attr: { name: "value", value: "Channel Performance Analysis" } }, { sel: ".mh-skill-form__field select", attr: { name: "data-value", value: "D2C Insights" } }], [{ eval: "document.querySelector('.mh-skill-form__field select').setAttribute('data-value', document.querySelector('.mh-skill-form__field select').value)" }]) },
  // The play function traverses Edit → Cancel → Create; wait for Create before checking the live input value.
  { id: "p15-create-after-edit", original: { url, actions: [{ click: '.scenario-row:first-child' }, { click: "#detailEditBtn" }, { click: "#cancelEditBtn" }, { click: "#createNewScenarioBtn" }, { eval: "document.querySelector('#scenarioName').setAttribute('data-value', document.querySelector('#scenarioName').value)" }], expect: [{ sel: "#scenarioEditView:not([hidden])", text: "Scenario Configuration" }, { sel: "#scenarioName", attr: { name: "data-value", value: "Channel Performance Analysis" } }] }, story: story("create-after-edit", [{ sel: ".mh-skill-form", text: "Scenario Configuration" }, { sel: ".mh-skill-form__field input", attr: { name: "data-value", value: "" } }], [{ wait: '.mh-skill-page[data-skill-mode="create"]' }, { eval: "document.querySelector('.mh-skill-form__field input').setAttribute('data-value', document.querySelector('.mh-skill-form__field input').value)" }]) },
  // KS-07: React saves the submitted skill as Under Review (10th row, Untitled) and toasts; the source discards the form.
  { id: "p15-blank-submit", original: { url, actions: [{ click: "#createNewScenarioBtn" }, { click: '.scenario-edit-form .scenario-edit-btn.primary' }], expect: [{ sel: "#scenarioEditView[hidden]", state: "attached", attr: { name: "hidden", value: "" } }, { sel: ".scenario-row", count: 9 }] }, story: story("blank-submit", [{ sel: ".mh-skill-form", count: 0, state: "detached" }, { sel: ROW, count: 10 }, { sel: ".mh-toast", text: "Submitted for review" }], [{ wait: ROW }]) },
  { id: "p15-submit", original: { url, actions: [{ click: "#createNewScenarioBtn" }, { fill: ["#scenarioName", "Quarterly pacing"] }, { click: '.scenario-edit-form .scenario-edit-btn.primary' }], expect: [{ sel: "#scenarioEditView[hidden]", state: "attached", attr: { name: "hidden", value: "" } }] }, story: story("create", [{ sel: ".mh-skill-form", count: 0, state: "detached" }, { sel: ROW, count: 10 }, { sel: `${ROW}:first-child`, text: "Quarterly pacing" }, { sel: `${ROW}:first-child`, text: "Under Review" }, { sel: ".mh-toast", text: "Submitted for review" }], [{ fill: [".mh-skill-form__field input", "Quarterly pacing"] }, { click: ".mh-skill-form__submit" }]) },
  { id: "p15-clear", original: { url, actions: [{ fill: ["#scenarioSearch", "no matching scenario"] }], expect: [{ sel: "#emptyState:not([hidden])", text: "No matching scenarios" }] }, story: story("", [{ sel: ROW, count: 9 }], [{ fill: [".mh-library-toolbar__search input", "no matching scenario"] }, { click: ".mh-library-empty button" }]) },
  { id: "p15-delete", original: { url, actions: [{ click: ".scenario-row:first-child" }], expect: [{ sel: ".scenario-detail-drawer.open #detailDeleteBtn", text: "Delete" }] }, story: story("", [{ sel: ROW, count: 8 }, { sel: ".mh-skill-detail", count: 0, state: "detached" }, { sel: ".mh-toast", text: "Deleted successfully" }], [{ click: `${ROW}:first-child` }, { click: ".mh-skill-detail__actions .mh-button--danger" }, { click: ".mh-confirm__btn--primary" }]) },
  { id: "p15-autofill", original: { url, actions: [{ click: "#createNewScenarioBtn" }], expect: [{ sel: "#scenarioEditView:not([hidden]) .scenario-edit-ai-fill", count: 5 }] }, story: story("create", [{ sel: ".mh-skill-form__card textarea:not(:placeholder-shown)", count: 1 }], [{ click: ".mh-autofill button >> nth=0" }]) },
  { id: "p15-run-preview", original: { url, actions: [{ click: '.scenario-row:first-child' }, { click: "#detailEditBtn" }], expect: [{ sel: "#scenarioEditView:not([hidden]) #runPreviewBtn", text: "Run Preview" }] }, story: story("edit", [{ sel: ".mh-example-preview__body pre", text: "Generating preview for:" }, { sel: ".mh-example-preview__body textarea", count: 1 }], [{ click: ".mh-example-preview__head button" }]) },
  { id: "p15-save-draft", original: { url, actions: [{ click: "#createNewScenarioBtn" }], expect: [{ sel: '#scenarioEditView:not([hidden]) .scenario-edit-form-actions button:has-text("Save Draft")', text: "Save Draft" }] }, story: story("create", [{ sel: ".mh-toast", text: "Draft saved" }, { sel: ".mh-skill-form", text: "Scenario Configuration" }], [{ fill: [".mh-skill-form__field input", "Draft scenario"] }, { click: '.mh-skill-form__footer button:has-text("Save Draft")' }]) },
  { id: "p15-assistant", original: { url, actions: [{ click: ".global-ai-launcher" }], expect: [{ sel: "#assistantPanel:not([hidden])", text: "Ask AI Interpreter" }] }, story: story("assistant", [{ sel: ".mh-assistant", text: "Ask AI Interpreter" }, { sel: ".mh-launcher", count: 1, state: "hidden" }]) },
];
