/** P16 Scenario Detail: source-reachable panels, preview, record selection and lite assistant. */
const url = "/assets/pages/scenario-detail.html";
const original = (id, actions = [], expect = []) => ({ url: id ? `${url}?id=${id}` : url, actions, expect });
const storySuffix = { "campaign-review-record": "known", "unknown-id-falls-back-to-first-skill": "unknown", "related-objects": "related", "usage-feedback": "usage", "version-history": "version", "activity-log": "activity", "preview-example-output": "preview", "assistant-open": "assistant", "suggestion-fills-prompt": "assistant-filled", "recent-chats": "assistant-history", "skill-menu": "assistant-skills", "selected-model": "assistant-selected", "model-chat-history": "model-history", "manual-model": "model-manual", "generated-model": "model-generated", "model-required-fields": "model-error", "model-needs-a-selected-message": "model-empty" };
const story = (id, expect, actions = []) => ({ id: `pages--scenario-detail${id ? `-${storySuffix[id] || id}` : ""}`, expect, actions });
const sourceTab = (name, panel, text) => original(null, [{ click: `.scenario-detail-tab[data-tab='${name}']` }], [{ sel: `.scenario-detail-tab[data-tab='${name}'][aria-pressed='true']` }, { sel: `${panel}:not([hidden])`, text }]);
const reactTab = (name, text) => story(name, [{ sel: `.mh-scenario-detail[data-scenario-tab='${name === "ai-check" ? "ai-check" : name}']` }, { sel: `.mh-scenario-detail__panel [data-scenario-panel='${name}']`, text }]);

export default [
  { id: "p16-default", original: original(null, [], [{ sel: "#heroStatus", text: "In Development" }, { sel: "#scenarioName", text: "City Comparison Analysis" }, { sel: ".scenario-detail-structure-item", count: 5 }, { sel: "#tab-content .scenario-detail-governance-item", count: 9 }]), story: story("", [{ sel: '.mh-scenario-detail-page[data-scenario-id="city-comparison"]' }, { sel: ".mh-scenario-detail__info-head h2", text: "City Comparison Analysis" }, { sel: ".mh-scenario-structure__item", count: 5 }, { sel: ".mh-scenario-governance__item", count: 9 }]) },
  { id: "p16-known-record", original: original("scenario-campaign-review", [], [{ sel: "#heroStatus", text: "Published" }, { sel: "#heroVersion", text: "v1.0" }, { sel: "#scenarioName", text: "Campaign Review Reporting" }, { sel: "#govKnowledgeId", text: "SCN-CR-001" }]), story: story("campaign-review-record", [{ sel: '.mh-scenario-detail-page[data-scenario-id="scenario-campaign-review"]' }, { sel: ".mh-scenario-detail__info-head h2", text: "Campaign Review Reporting" }, { sel: ".mh-scenario-governance__item:first-child", text: "SCN-CR-001" }]) },
  { id: "p16-unknown-record", original: original("no-such-skill", [], [{ sel: "#heroLikeRate", text: "91%" }, { sel: "#scenarioName", text: "Channel Performance Analysis" }]), story: story("unknown-id-falls-back-to-first-skill", [{ sel: '.mh-scenario-detail-page[data-scenario-id="scenario-channel-performance"]' }, { sel: ".mh-scenario-detail__info-head h2", text: "Channel Performance Analysis" }]) },
  { id: "p16-edit-id-correction", original: original("scenario-campaign-review", [{ eval: "if (document.querySelector('.scenario-detail-edit-btn').getAttribute('href') !== 'scenario-edit.html') throw new Error('original edit unexpectedly preserved id')" }], [{ sel: ".scenario-detail-edit-btn", text: "Edit Scenario" }]), story: story("campaign-review-record", [{ sel: '.mh-scenario-detail__edit[href*="id=scenario-campaign-review"]', text: "Edit Scenario" }]) },
  { id: "p16-related", original: sourceTab("related", "#tab-related", "Invest City Strategy Analysis"), story: reactTab("related", "Invest City Strategy Analysis") },
  { id: "p16-related-links", original: original(null, [{ click: ".scenario-detail-tab[data-tab='related']" }], [{ sel: "#tab-related a[href='reports.html']", count: 2 }, { sel: "#tab-related a[href='knowledge.html']", count: 2 }, { sel: "#tab-related .scenario-related-card", count: 4 }]), story: story("related-objects", [{ sel: ".mh-scenario-detail__related-grid a", count: 4 }, { sel: ".mh-scenario-detail__related-grid a:first-child", text: "Invest City Strategy Analysis" }, { sel: ".mh-scenario-detail__related-grid a:last-child", text: "Weekly City Performance Readout" }]) },
  { id: "p16-ai-check", original: sourceTab("ai-check", "#tab-ai-check", "AI Checked — Analysis Scenario"), story: story("ai-check", [{ sel: ".mh-scenario-detail__ai-check", text: "AI Checked — Analysis Scenario" }, { sel: ".mh-scenario-detail__ai-field--filled", count: 8 }, { sel: ".mh-scenario-detail__ai-field--missing", count: 2 }]) },
  { id: "p16-usage", original: sourceTab("usage", "#tab-usage", "386 / 30 days"), story: story("usage-feedback", [{ sel: ".mh-scenario-detail__usage", text: "386 / 30 days" }, { sel: ".mh-scenario-detail__usage .mh-scenario-detail__governance-item", count: 4 }]) },
  { id: "p16-version", original: sourceTab("version", "#tab-version", "Added anomaly detection step"), story: story("version-history", [{ sel: ".mh-scenario-detail__version-row", count: 4 }, { sel: ".mh-scenario-detail__version-row:first-child", text: "Added anomaly detection step" }]) },
  { id: "p16-activity", original: sourceTab("activity", "#tab-activity", "Scenario published"), story: story("activity-log", [{ sel: ".mh-scenario-detail__activity-row", count: 4 }, { sel: ".mh-scenario-detail__activity-row:last-child", text: "Scenario published" }]) },
  { id: "p16-preview", original: original(null, [{ click: "#previewToggle" }], [{ sel: "#previewContent:not([hidden])", text: "Compare media investment performance" }, { sel: "#previewOutput", text: "City Comparison: Shanghai vs Beijing" }, { sel: "#previewToggle", text: "Hide Preview" }]), story: story("preview-example-output", [{ sel: ".mh-scenario-preview__body", text: "Compare media investment performance" }, { sel: ".mh-scenario-preview__output", text: "City Comparison: Shanghai vs Beijing" }, { sel: ".mh-scenario-preview button[aria-expanded='true']", text: "Hide Preview" }]) },
  { id: "p16-preview-close", original: original(null, [{ click: "#previewToggle" }, { click: "#previewToggle" }], [{ sel: "#previewContent[hidden]", state: "attached" }, { sel: "#previewToggle", text: "Show Preview" }]), story: story("preview-example-output", [{ sel: ".mh-scenario-preview__body", count: 0, state: "detached" }, { sel: ".mh-scenario-preview button[aria-expanded='false']", text: "Show Preview" }], [{ click: ".mh-scenario-preview button" }]) },
  { id: "p16-content-bottom", original: original(null, [{ eval: "window.scrollTo(0, document.body.scrollHeight)" }, { waitMs: 200 }], [{ sel: ".scenario-detail-usage-link", text: "Used in 42 Reports / 6 Scenarios" }, { sel: "#tab-content .scenario-detail-governance-item", count: 9 }]), story: story("", [{ sel: ".mh-scenario-detail__usage-link", text: "Used in 42 Reports / 6 Scenarios" }, { sel: ".mh-scenario-governance__item", count: 9 }], [{ eval: "window.scrollTo(0, document.body.scrollHeight)" }, { waitMs: 200 }]) },
  { id: "p16-narrow", viewport: { width: 390, height: 844 }, original: original(null, [], [{ sel: "#scenarioName", text: "City Comparison Analysis" }, { sel: ".scenario-detail-tab", count: 6 }]), story: story("", [{ sel: ".mh-scenario-detail__info-head h2", text: "City Comparison Analysis" }, { sel: ".mh-scenario-detail__tabs button", count: 6 }]) },
  { id: "p16-assistant-open", original: original(null, [{ click: ".global-ai-launcher" }], [{ sel: "#assistantPanel:not([hidden])", text: "Ask a question" }, { sel: ".global-ai-launcher", state: "hidden" }]), story: story("assistant-open", [{ sel: ".mh-assistant", text: "Ask a question" }, { sel: ".mh-launcher", state: "hidden" }]) },
  { id: "p16-assistant-fill", original: original(null, [{ click: ".global-ai-launcher" }, { click: ".ask-suggestion:first-child" }], [{ sel: "#promptCanvas", text: "Definition of Attributed ROI" }, { sel: "#answerFeed .answer-card", count: 0, state: "detached" }]), story: story("suggestion-fills-prompt", [{ sel: ".mh-assistant__send button:not([disabled])", count: 1 }, { sel: ".mh-assistant__answer", count: 0, state: "detached" }], [{ eval: "if (document.querySelector('.mh-assistant__box textarea').value !== 'Definition of Attributed ROI') throw new Error('suggestion prompt missing')" }]) },
  { id: "p16-assistant-answer", original: original(null, [{ click: ".global-ai-launcher" }, { fill: ["#promptCanvas", "Definition of Attributed ROI"] }, { click: "#sendQuery" }], [{ sel: "#answerFeed .answer-card", text: "I will use the AI Interpreter knowledge context to answer:" }]), story: story("assistant-answer", [{ sel: ".mh-assistant__answer--simple", text: "I will use the AI Interpreter knowledge context to answer:" }]) },
  { id: "p16-assistant-history", original: original(null, [{ click: ".global-ai-launcher" }, { click: "#aiHistory" }], [{ sel: "#aiRecentHistoryPopup:not([hidden])", text: "Summarize the latest media tracking performance." }]), story: story("recent-chats", [{ sel: ".mh-assistant__history-pop", text: "Summarize the latest media tracking performance." }]) },
  { id: "p16-assistant-maximize", original: original(null, [{ click: ".global-ai-launcher" }, { click: "#aiMaximize" }], [{ sel: "#assistantPanel.is-ai-expanded", text: "Ask AI Interpreter" }]), story: story("assistant-maximized", [{ sel: ".mh-assistant--expanded", text: "Ask AI Interpreter" }]) },
  { id: "p16-assistant-skill", original: original(null, [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }], [{ sel: "#aiSkillMenu:not([hidden])", text: "Analytical Model" }]), story: story("skill-menu", [{ sel: ".mh-skill", text: "Analytical Model" }]) },
  { id: "p16-assistant-selected", original: original(null, [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: ".ai-skill-option:has-text('ROI diagnosis')" }], [{ sel: ".ai-skill-chip:not([hidden])", text: "ROI diagnosis model" }]), story: story("selected-model", [{ sel: ".mh-assistant__chip", text: "ROI diagnosis model" }]) },
  { id: "p16-model-history", original: original(null, [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='history']" }], [{ sel: ".ai-flow-dialog", text: "Generate Analytical Model" }]), story: story("model-chat-history", [{ sel: ".mh-flow", text: "Generate Analytical Model" }]) },
  { id: "p16-model-manual", original: original(null, [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='manual']" }], [{ sel: "#aiGeneratedModelDialog .ai-model-form-card", text: "Create Analytical Model Manually" }]), story: story("manual-model", [{ sel: ".mh-flow__card--form", text: "Create Analytical Model Manually" }]) },
  { id: "p16-model-generated", original: original(null, [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='history']" }, { click: "[data-ai-generate-model]" }], [{ sel: "#aiGeneratedModelDialog .ai-model-form-card", text: "New Analytical Model" }]), story: story("generated-model", [{ sel: ".mh-flow__card--form", text: "New Analytical Model" }]) },
  { id: "p16-model-required", original: original(null, [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='manual']" }, { click: "[data-ai-submit-model]" }], [{ sel: "#aiGeneratedModelDialog .field-error", count: 3, text: "is required" }]), story: story("model-required-fields", [{ sel: ".mh-flow__field-error", count: 3, text: "is required" }]) },
  { id: "p16-model-empty", original: original(null, [{ click: ".global-ai-launcher" }, { click: "#uploadFile" }, { click: ".ai-skill-category[data-ai-skill-category='Analytical Model']" }, { click: "[data-ai-skill-action='history']" }, { eval: "document.querySelectorAll('#aiHistoryGenerateDialog [data-ai-history-msg]:checked').forEach(el => el.click())" }, { click: "[data-ai-generate-model]" }], [{ sel: "[data-ai-generate-error]:not([hidden])", text: "Select at least one message to continue." }]), story: story("model-needs-a-selected-message", [{ sel: ".mh-flow__error", text: "Select at least one message to continue." }]) },
  { id: "p16-assistant-new-session", original: original(null, [{ click: ".global-ai-launcher" }, { fill: ["#promptCanvas", "Definition of Attributed ROI"] }, { click: "#sendQuery" }, { click: "#aiNewSession" }], [{ sel: "#answerFeed", state: "hidden" }, { sel: "#sendQuery[disabled]", count: 1 }]), story: story("assistant-answer", [{ sel: ".mh-assistant__answer", count: 0, state: "detached" }, { sel: ".mh-assistant__send button[disabled]", count: 1 }], [{ click: "button[aria-label='New session']" }]) },
  { id: "p16-assistant-enter", original: original(null, [{ click: ".global-ai-launcher" }, { fill: ["#promptCanvas", "Line one"] }, { press: ["#promptCanvas", "Enter"] }], [{ sel: "#answerFeed .answer-card", count: 0, state: "detached" }, { sel: "#sendQuery:not([disabled])" }]), story: story("assistant-open", [{ sel: ".mh-assistant__answer", count: 0, state: "detached" }, { sel: ".mh-assistant__send button:not([disabled])" }], [{ fill: [".mh-assistant__box textarea", "Line one"] }, { press: [".mh-assistant__box textarea", "Enter"] }]) },
  { id: "p16-assistant-escape", original: original(null, [{ click: ".global-ai-launcher" }, { press: ["body", "Escape"] }], [{ sel: "#assistantPanel[hidden]", state: "attached" }, { sel: ".global-ai-launcher", text: "AI Interpreter" }]), story: story("assistant-open", [{ sel: ".mh-assistant", count: 0, state: "detached" }, { sel: ".mh-launcher", text: "AI Interpreter" }], [{ press: ["body", "Escape"] }]) },
];
