/** P17 Skill Edit: the visible form, preview, required gates, navigation and lite assistant. */
import p14 from "./p14.mjs";

const url = "/assets/pages/scenario-edit.html";
const story = (id, expect, actions = []) => ({ id: `pages--scenario-edit${id ? `-${id}` : ""}`, expect, actions });
const textValue = (selector, expected, side) => ({ eval: `if (document.querySelector(${JSON.stringify(selector)})?.value !== ${JSON.stringify(expected)}) throw new Error(${JSON.stringify(`${side} value mismatch: ${selector}`)})` });
const sourceStates = [
  { id: "p17-default", original: { url, expect: [{ sel: ".scenario-edit-form-header", text: "Scenario Configuration" }, { sel: ".scenario-edit-structure-item", count: 4 }, { sel: "#previewContent", state: "hidden" }], actions: [textValue("#scenarioName", "City Comparison Analysis", "source")] }, story: story("", [{ sel: ".mh-scenario-edit-form__header", text: "Scenario Configuration" }, { sel: ".mh-scenario-edit-form__card", count: 4 }, { sel: ".mh-example-preview__body", count: 0, state: "detached" }], [textValue('.mh-scenario-edit-form__field input', "City Comparison Analysis", "story")]) },
  { id: "p17-known", original: { url: `${url}?id=scenario-campaign-review`, actions: [textValue("#scenarioName", "Campaign Review Reporting", "source"), textValue("#scenarioScope", "", "source")], expect: [{ sel: ".scenario-edit-form-header", text: "Scenario Configuration" }, { sel: "#editReportLink", text: "Open Invest City Strategy Analysis" }] }, story: story("known", [{ sel: ".mh-scenario-edit-form__header", text: "Scenario Configuration" }, { sel: ".mh-scenario-edit-form__card-body a", text: "Open Invest City Strategy Analysis" }], [textValue('.mh-scenario-edit-form__field input', "Campaign Review Reporting", "story"), textValue('.mh-scenario-edit-form__field select', "DC Media Performance", "story")]) },
  { id: "p17-unknown-fallback", original: { url: `${url}?id=unknown-skill`, actions: [textValue("#scenarioName", "City Comparison Analysis", "source")], expect: [{ sel: ".scenario-edit-form-header", text: "Scenario Configuration" }] }, story: story("", [{ sel: ".mh-scenario-edit-form__header", text: "Scenario Configuration" }], [textValue('.mh-scenario-edit-form__field input', "City Comparison Analysis", "story")]) },
  { id: "p17-report-selected", original: { url, actions: [{ select: ["#editReport", "Creative Quality Monitor"] }], expect: [{ sel: "#editReportLink:not([hidden])", text: "Open Creative Quality Monitor", attr: { name: "href", value: "../pages/reports.html?project=rednote&dashboard=1" } }] }, story: story("report-changed", [{ sel: ".mh-scenario-edit-form__card-body a", text: "Open Creative Quality Monitor", attr: { name: "href", value: "/assets/pages/reports.html?project=rednote&dashboard=1" } }]) },
  { id: "p17-report-empty", original: { url, actions: [{ select: ["#editReport", ""] }], expect: [{ sel: "#editReportLink", state: "hidden", attr: { name: "hidden", value: "" } }, { sel: "#editReport" }] }, story: story("report-empty", [{ sel: ".mh-scenario-edit-form__card-body a", count: 0, state: "detached" }, { sel: ".mh-scenario-edit-form__card-body select" }]) },
  { id: "p17-preview", original: { url, actions: [{ click: "#runPreviewBtn" }], expect: [{ sel: "#previewContent:not([hidden])", text: "Generating preview for:" }, { sel: "#previewOutput", text: "Unified Dimension" }] }, story: story("preview", [{ sel: ".mh-example-preview__body pre", text: "Generating preview for:" }, { sel: ".mh-example-preview__body pre", text: "Unified Dimension" }]) },
  { id: "p17-preview-empty", original: { url, actions: [{ click: "#runPreviewBtn" }, { fill: ["#previewQuestion", ""] }, { click: "#runPreviewBtn" }], expect: [{ sel: "#previewOutput", text: "Please enter an example question first." }] }, story: story("preview-empty", [{ sel: ".mh-example-preview__body pre", text: "Please enter an example question first." }]) },
  { id: "p17-required", original: { url: `${url}?id=scenario-campaign-review`, actions: [{ fill: ["#scenarioName", ""] }, { fill: ["#scenarioPurpose", ""] }, { fill: ["#scenarioOwner", ""] }, { select: ["#editReport", ""] }, { click: '.scenario-edit-btn.primary' }], expect: [{ sel: ".field-error-msg:not([hidden])", count: 5, text: "Cannot be empty" }] }, story: story("required", [{ sel: '[aria-invalid="true"]', count: 5 }, { sel: 'small[role="alert"]', count: 5, text: "Cannot be empty" }]) },
  { id: "p17-input-change", original: { url, actions: [{ fill: ["#scenarioName", "Updated city analysis"] }, textValue("#scenarioName", "Updated city analysis", "source")], expect: [{ sel: ".scenario-edit-form-header", text: "Scenario Configuration" }] }, story: story("", [{ sel: ".mh-scenario-edit-form__header", text: "Scenario Configuration" }], [{ fill: [".mh-scenario-edit-form__field input", "Updated city analysis"] }, textValue(".mh-scenario-edit-form__field input", "Updated city analysis", "story")]) },
  { id: "p17-autofill", original: { url, expect: [{ sel: ".scenario-edit-ai-fill", count: 2 }] }, story: story("", [{ sel: ".mh-scenario-edit-form__header", text: "Scenario Configuration" }], [{ click: '.mh-scenario-edit-form__fill button >> nth=0' }, textValue('.mh-scenario-edit-form__fill textarea', "Confirm report context -> Compare periods -> Decompose drivers -> Explain exceptions -> Recommend next actions", "story")]) },
  { id: "p17-save-draft", original: { url, expect: [{ sel: '.scenario-edit-form-actions button:has-text("Save Draft")', text: "Save Draft" }] }, story: story("", [{ sel: ".mh-toast", text: "Draft saved" }, { sel: ".mh-scenario-edit-form", text: "Scenario Configuration" }], [{ click: '.mh-scenario-edit-form__actions button[type="button"]' }]) },
  { id: "p17-file-selection", original: { url, actions: [{ upload: ["#editAttachments", { name: "sample-note.pdf", content: "local fixture" }] }, { eval: "if (document.querySelector('#editAttachments').files.length !== 1) throw new Error('source native file selection missing')" }], expect: [{ sel: ".scenario-edit-attachment-pill", count: 2 }] }, story: story("", [{ sel: ".mh-scenario-edit-form__attachments span", count: 2 }], [{ upload: ['.mh-scenario-edit-form__upload input[type="file"]', { name: "sample-note.pdf", content: "local fixture" }] }, { eval: "if (document.querySelector('.mh-scenario-edit-form__upload input').files.length !== 1) throw new Error('story native file selection missing')" }]) },
  { id: "p17-bottom", original: { url, actions: [{ eval: "window.scrollTo(0,document.body.scrollHeight)" }], expect: [{ sel: ".scenario-edit-form-actions", text: "Submit for Review" }, { sel: ".scenario-edit-attachment-pill", count: 2 }] }, story: story("", [{ sel: ".mh-scenario-edit-form__actions", text: "Submit for Review" }, { sel: ".mh-scenario-edit-form__attachments span", count: 2 }], [{ eval: "window.scrollTo(0,document.body.scrollHeight)" }]) },
  { id: "p17-narrow", viewport: { width: 390, height: 844 }, original: { url, expect: [{ sel: ".scenario-edit-form-header", text: "Scenario Configuration" }, { sel: ".scenario-edit-structure-item", count: 4 }] }, story: story("", [{ sel: ".mh-scenario-edit-form__header", text: "Scenario Configuration" }, { sel: ".mh-scenario-edit-form__card", count: 4 }]) },
];

const assistantStates = p14.filter((item) => item.id.startsWith("p14-assistant-") || item.id.startsWith("p14-model-")).map((item) => ({ ...item, id: item.id.replace(/^p14-/, "p17-"), original: { ...item.original, url }, story: { ...item.story, id: item.story.id.replace("pages--personal-memory", "pages--scenario-edit") } }));

export default [...sourceStates, ...assistantStates];
